Repository dogecoin/dogecoin.com, pull requests merged in 2021-04, with the labels that each got.

#150 Tune docker guide run params
  getting-started/contribute_docker.md
Labels: documentation

#144 FaH instead of Faucet
  README.md
  assets/i18n/de.json
  assets/i18n/doge.json
  assets/i18n/en.json
  assets/i18n/es.json
  assets/i18n/fr.json
  getting-started/contribute_osx.md
  index.html
Labels: content change

#151 Updated the styling
  assets/css/styles.css
Labels: enhancement

#157 Update CNAME for www subdomain
  CNAME
Labels: bug

#148 added support page with text and links
  assets/css/styles.css
  assets/i18n/en.json
  support.html
Labels: content change, enhancement
